### Never send your "passwords" in Production ###

x-base: &common
  build:
    dockerfile: Dockerfile
  restart: unless-stopped
  networks:
    - podman
  deploy:
    resources:
      limits:
        cpus: 2
        memory: 2048M
        pids: 200
  memswap_limit: 4096M
  logging:
    options:
      max-size: 10M
      max-file: 3
  security_opt:
    - no-new-privileges=true
  environment:
    - PUID=1000
    - PGID=1000

services:
  express-graphql-dev:
    <<: *common
    build:
      context: ./express-graphql
      target: dev
    image: lipebol/express-graphql-dev
    container_name: express-graphql-dev
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./express-graphql:/home/node/express-graphql
  
  osrm-bicycle:
    <<: *common
    build:
      context: ./osrm-backend
      target: osrm-bicycle
    image: lipebol/osrm-backend
    container_name: osrm-bicycle
    tty: true
    command: |
      bash -c "osrm-routed --algorithm mld /data/illinois-latest.osrm"
    expose: 
      - 5000
    volumes:
      - osrm-data:/data

networks:
  podman:
    external: true

volumes:
  osrm-data:
    external: true